server:
  port: 80
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     #defaultZone: http://localhost:7001/eureka
      defaultZone: http://peer2:7002/eureka,http://peer1:7001/eureka/  #集群版
spring:
  application:
    name: cloud-consumer-order