server:
  port: 8001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
    #单机版
      defaultZone: http://localhost:7001/eureka
      #集群版
      #defaultZone: http://peer2:7002/eureka,http://peer1:7001/eureka/
spring:
  application:
    name: cloud-provider-hystrix-payment-8001
