server:
  port: 9527
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
    #单机版
      defaultZone: http://localhost:7001/eureka
  instance:
    hostname: cloud-gateway-server
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的id
          #uri: http://localhost:8001 #服务地址
          uri: lb://cloud-provider-payment
          predicates:
            - Path=/payment/get/**
        - id: payment_routh2 #路由的id
          #uri: http://localhost:8001 #服务地址
          uri: lb://cloud-provider-payment
          predicates:
            - Path=/payment/lb/**
            - After=2020-03-11T13:12:18.263+08:00[Asia/Shanghai]
            #- Cookie=username,zzyy 加入带cookie
            #- Header=X-Request-Id, \d+ #值为整数的正则表达式

      discovery:
        locator:
          enabled: true #开启 动态路由 微服务名称






